#!/bin/sh
#
# Usage: asn <ip|asn>
# Description: fetch as network information

asn () {
    if [[ $1 =~ ^(AS)?[0-9]+$ ]]
    then
        asn="AS${1#AS}"
    else
        info=$(dig $1.origin.asn.cymru.com TXT +short)
        info="${info#\"\\}"
        info="${info#\"}"
        info="${info%\"}"
        info="${info%\\\"}"
        echo $info
        asn="AS${info%% *}"
    fi
    asn_info=$(dig ${asn}.asn.cymru.com TXT +short)
    asn_info="${asn_info#\"\\}"
    asn_info="${asn_info#\"}"
    asn_info="${asn_info%\"}"
    asn_info="${asn_info%\\\"}"
    echo $asn_info
}
